# Configuração do cluster Kind
# kind: tipo do recurso (Cluster para configuração do Kind)
# apiVersion: versão da API do Kind
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

# nodes: define os nós do cluster
nodes:
  # Control Plane: gerencia o estado do cluster
  # Executa: kube-apiserver, kube-scheduler, kube-controller-manager, etcd
  - role: control-plane

  # Worker Node: executa as cargas de trabalho (pods)
  # Executa: kubelet, kube-proxy, container runtime
  - role: worker
